"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read environment variables, with type casting and defaults via django-environ.
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['127.0.0.1', 'localhost']),
)
# Load a local .env file if present (not committed to version control).
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'imagekit',
    'tinymce',
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.navigation',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db(
        'DATABASE_URL',
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (item photos uploaded by the owner via the admin)
# https://docs.djangoproject.com/en/6.0/topics/files/
#
# Uploaded photos are stored on the local disk under MEDIA_ROOT.
#   - Development: Django serves them via the static() helper in config/urls.py
#     (active only when DEBUG=True).
#   - Production: Django does NOT serve media. Nginx serves MEDIA_ROOT directly
#     with a `location /media/ { alias <MEDIA_ROOT>/; }` block (see deploy step).
#
# >>> BACKUPS: MEDIA_ROOT MUST be included in production backups. <<<
# A database dump alone will NOT restore the shop — the item photos live here on
# disk, not in PostgreSQL. Back up MEDIA_ROOT alongside the pg_dump, on the same
# schedule. (Generated thumbnails under MEDIA_ROOT/CACHE are regenerable from the
# originals, but the original uploads are irreplaceable.)
MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'

# django-imagekit: generated thumbnails are cached on disk under
# MEDIA_ROOT/CACHE and created lazily on first access (JustInTime strategy).
# They are derived from the original uploads, so they need no separate backup.

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Rich-text editor (django-tinymce) for writing Information articles in the admin.
# Self-hosted from the package's bundled static files — no API key or CDN.
# A deliberately small toolbar keeps the editor friendly for a non-technical writer.
TINYMCE_DEFAULT_CONFIG = {
    'height': 420,
    'menubar': False,
    'branding': False,
    'promotion': False,
    'plugins': 'autoresize lists link',
    'toolbar': (
        'undo redo | blocks | bold italic | bullist numlist | '
        'link blockquote | removeformat'
    ),
    'block_formats': 'Paragraph=p; Heading=h2; Subheading=h3',
}
