# Generated by Django 6.0.6 on 2026-06-20 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='Choose a category. You can add new categories under “Categories” on the main admin page.', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(blank=True, choices=[('mint', 'Mint'), ('excellent', 'Excellent'), ('very_good', 'Very good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('for_restoration', 'For restoration')], help_text='Overall condition of the piece (optional).', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(default='USD', help_text='3-letter currency code. Leave as USD unless you price in another currency.', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text="Describe the piece and its story — anything a buyer would like to know. This shows on the item's page."),
        ),
        migrations.AlterField(
            model_name='item',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Size of the piece, for example "H 90 × W 45 × D 30 cm".', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='era',
            field=models.CharField(blank=True, help_text='Period or era, for example "Victorian", "Art Deco", or "1960s".', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='featured',
            field=models.BooleanField(default=False, help_text='Tick to highlight this item in the featured section.', verbose_name='feature on homepage'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price, numbers only (for example 249.99).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='provenance',
            field=models.TextField(blank=True, help_text='Where it came from or its history, if known.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sold_at',
            field=models.DateTimeField(blank=True, help_text='Filled in automatically when the item is marked sold.', null=True, verbose_name='date sold'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', help_text="“Available” = for sale. “Reserved” = on hold for someone. “Sold” = sold — this is permanent and can't be undone.", max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(help_text='The name of the piece as it will appear on the website.', max_length=200),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='A few words describing the photo (helps search engines and visually-impaired visitors). Optional.', max_length=200),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(help_text='Upload a photo. Large phone photos are fine — small versions for the website are made automatically.', upload_to='items/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first (0, 1, 2 …).', verbose_name='display order'),
        ),
    ]
