# Generated by Django 6.0.6 on 2026-06-25 15:45

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_item_category_alter_item_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The article's headline, as it will appear on the website.", max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Filled in automatically from the title.', max_length=220, unique=True)),
                ('intro', models.CharField(blank=True, help_text='A short summary shown in the article list (optional — if left blank, the start of the article is used).', max_length=300)),
                ('header_image', models.ImageField(blank=True, help_text='Optional photo shown at the top of the article and in the list.', upload_to='articles/%Y/%m/')),
                ('body', tinymce.models.HTMLField(blank=True, help_text='Write your article here.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='“Draft” is only visible to you. “Published” shows on the website.', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='Filled in automatically the first time the article is published.', null=True, verbose_name='date published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='shop_articl_status_398b25_idx'), models.Index(fields=['slug'], name='shop_articl_slug_bf7c2c_idx')],
            },
        ),
    ]
