# Generated by Django 6.0.6 on 2026-06-26 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Choose one or more categories. You can add new categories under “Categories” on the main admin page.', related_name='items', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Legacy field — will be removed after migration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_old', to='shop.category'),
        ),
    ]
