# Generated by Django 6.0.6 on 2026-06-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_populate_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
